export const __prod__ = process.env.NODE_ENV === 'production'
export const COOKIE_NAME = 'qid'
export const TEST_ACCOUNT_USER = 'pkcqszigsnlufge4@ethereal.email'
export const TEST_ACCOUNT_PASS = 'XACG172dXAFsvB2vft'
export const FORGET_PASSWORD_PREFIX = 'forget-password:'